# Generated by Django 5.2.8 on 2025-11-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='chefs/%y/%m/%d')),
                ('is_executive_chef', models.BooleanField()),
                ('years_of_work', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='awards/%y/%m/%d')),
                ('chefs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='pages.chef')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_before_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.PositiveSmallIntegerField(max_length=2)),
                ('image', models.ImageField(upload_to='food/%y/%m/%d')),
                ('image_description', models.ImageField(upload_to='food-description/%y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='pages_food_created_4dfd07_idx')],
            },
        ),
    ]
