# Generated by Django 5.2.8 on 2025-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_description',
        ),
        migrations.AddField(
            model_name='food',
            name='icon_description',
            field=models.CharField(choices=[('fire', 'fire'), ('leaf', 'leaf'), ('check-circle', 'check-circle'), ('star-fill', 'star-fill')], default='fire'),
            preserve_default=False,
        ),
    ]
