# Generated by Django 5.2.8 on 2025-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_food_image_description_food_icon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='its_popularties',
            field=models.CharField(default="Chef's Pick", max_length=20),
            preserve_default=False,
        ),
    ]
