# Generated by Django 5.2.8 on 2025-11-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_food_its_popularties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='its_popularties',
            new_name='special_badge',
        ),
    ]
