# Generated by Django 5.2.8 on 2025-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_its_popularties_food_special_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='spicy', max_length=40),
            preserve_default=False,
        ),
    ]
