# Generated by Django 5.2.8 on 2025-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.CharField(choices=[('vegetarian', 'vegetarian'), ('spicy', 'spicy'), ('gluten-free', 'gluten-free'), ('premium', 'premium')], default='spicy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('starters', 'starters'), ('main courses', 'main courses'), ('desserts', 'desserts'), ('beverages', 'beverages')]),
        ),
    ]
