# Generated by Django 5.2.8 on 2025-11-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_food_tag_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='special_badge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
