# Generated by Django 5.2.8 on 2025-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_cart_owner_alter_cartitems_quntatiy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='pages_food_created_4dfd07_idx',
        ),
        migrations.AddField(
            model_name='chef',
            name='chef_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['id'], name='pages_food_id_e189a8_idx'),
        ),
    ]
