# Generated by Django 5.2.8 on 2025-11-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_food_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='image',
        ),
        migrations.AddField(
            model_name='awards',
            name='icon',
            field=models.CharField(choices=[('award', 'award'), ('star', 'star'), ('trophy-fill', 'trophy-fill')], default='star'),
            preserve_default=False,
        ),
    ]
