# Generated by Django 5.2.8 on 2025-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_awards_image_awards_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%y/%m/%d'),
        ),
    ]
