# Generated by Django 5.2.8 on 2025-11-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_chef_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('icon', models.CharField(choices=[('instagram', 'instagram'), ('linkedin', 'linkedin')])),
                ('chefs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.chef')),
            ],
        ),
    ]
