# Generated by Django 5.2.8 on 2025-11-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='link_it_self',
        ),
    ]
