# Generated by Django 5.2.8 on 2025-11-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_rename_link_link_link_it_self'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='pages_food_id_e189a8_idx',
        ),
        migrations.AddField(
            model_name='food',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['-created'], name='pages_food_created_4dfd07_idx'),
        ),
    ]
