# Generated by Django 5.2.8 on 2025-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_food_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='restur-features/%y/%m/%d')),
            ],
        ),
    ]
