# Generated by Django 5.2.8 on 2025-11-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_resturfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturfeatures',
            old_name='feature',
            new_name='title',
        ),
    ]
