# Generated by Django 5.2.8 on 2025-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='user',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='email',
            field=models.EmailField(default='NO', max_length=254),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='full_name',
            field=models.CharField(default='S', max_length=80),
        ),
    ]
