# Generated by Django 5.2.8 on 2025-12-02 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='capacity_from',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='package',
            name='capacity_to',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='package',
            name='fetures',
            field=models.JSONField(default='["5-course gourmet menu"]'),
        ),
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.CharField(default='star', max_length=30),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package', to=settings.AUTH_USER_MODEL),
        ),
    ]
