# Generated by Django 5.2.8 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_package_capacity_from_package_capacity_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fetures',
            field=models.JSONField(default='{"fetures": "5-course gourmet menu"}'),
        ),
    ]
