# Generated by Django 5.2.8 on 2025-12-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_package_fetures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fetures',
            field=models.JSONField(default=list),
        ),
    ]
