# Generated by Django 5.2.8 on 2025-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='most_popular',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
