# Generated by Django 5.2.8 on 2025-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_package_most_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='per',
            field=models.CharField(default='person', max_length=50),
            preserve_default=False,
        ),
    ]
