# Generated by Django 5.2.8 on 2025-12-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_package_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='events/%y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='description',
            field=models.TextField(default='hello'),
        ),
    ]
