# Generated by Django 5.2.8 on 2025-12-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_event_imagegallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='category',
            field=models.CharField(default='food', max_length=40),
            preserve_default=False,
        ),
    ]
