# Generated by Django 5.2.8 on 2025-12-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_imagegallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='name',
            field=models.CharField(default='there is No', max_length=30),
            preserve_default=False,
        ),
    ]
