# Generated by Django 5.2.8 on 2025-12-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_imagegallery_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='pages.order'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['id'], name='pages_packa_id_3376e5_idx'),
        ),
    ]
