# Generated by Django 5.2.8 on 2025-12-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_tablebooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
